version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "ScreenComplete-Win64bit"
    main: "./cmd/screen_complete"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64

  - id: "ScreenComplete-Win32bit"
    main: "./cmd/screen_complete"
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - 386

  - id: "ScreenComplete-OSX"
    main: "./cmd/screen_complete"
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - configs/configs.json
      - configs/**/*
      - README.md
      - LICENSE
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude: