name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23.1'
      -
        name: Set up Cross-compile ENV
        run: |
          sudo apt update
          sudo apt install gcc libc6-dev
          sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt install libxkbcommon-dev
          sudo apt install xsel xclip
          sudo apt-get install gcc-multilib
          sudo apt-get install gcc-mingw-w64
          sudo apt install libz-mingw-w64-dev
      -
        name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      -
        name: GoReleaser Release
        run: goreleaser --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}